USE `feugodb`;

 
INSERT INTO `assets_type`(TYPE_NAME,TYPE_ID,ATTR_ID,ATTR_NAME,DEPT_ID,CURRENT_ID,PREFIX) VALUES ('固定资产','GDZC','SC','生产设施','1',1,'G');
INSERT INTO `assets_type`(TYPE_NAME,TYPE_ID,ATTR_ID,ATTR_NAME,DEPT_ID,CURRENT_ID,PREFIX) VALUES ('低值易耗品','DZYH','SH','生活设施','1',1,'D');
INSERT INTO `assets_type`(TYPE_NAME,TYPE_ID,ATTR_ID,ATTR_NAME,DEPT_ID,CURRENT_ID,PREFIX) VALUES ('信息设备','XXSB','SH','生活设施','1',1,'X');
INSERT INTO `assets_type`(TYPE_NAME,TYPE_ID,ATTR_ID,ATTR_NAME,DEPT_ID,CURRENT_ID,PREFIX) VALUES ('劳保用品','LBYP','SH','生活设施','1',1,'L');
INSERT INTO `assets_type`(TYPE_NAME,TYPE_ID,ATTR_ID,ATTR_NAME,DEPT_ID,CURRENT_ID,PREFIX) VALUES ('消防器材','XFQC','SC','生产设施','1',1,'F');
INSERT INTO `assets_type`(TYPE_NAME,TYPE_ID,ATTR_ID,ATTR_NAME,DEPT_ID,CURRENT_ID,PREFIX) VALUES ('娱乐设施','YLSS','SC','生产设施','1',1,'Y');
INSERT INTO `assets_type`(TYPE_NAME,TYPE_ID,ATTR_ID,ATTR_NAME,DEPT_ID,CURRENT_ID,PREFIX) VALUES ('房屋建筑','FWJZ','SC','生产设施','1',1,'JZ');
INSERT INTO `assets_type`(TYPE_NAME,TYPE_ID,ATTR_ID,ATTR_NAME,DEPT_ID,CURRENT_ID,PREFIX) VALUES ('临时资产','LSZC','SH','生活设施','1',1,'LS');
INSERT INTO `assets_type`(TYPE_NAME,TYPE_ID,ATTR_ID,ATTR_NAME,DEPT_ID,CURRENT_ID,PREFIX) VALUES ('机器设备','JQSB','SH','生活设施','1',1,'JQ');


