
USE `feugodb`;

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',1);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',2);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',22);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',10000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',11000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',12000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',13000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',14000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',15000);

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',20000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',21000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',22000);

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',30000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',31000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',33000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',40000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',41000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',42000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',43000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',44000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',45000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',50000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',51000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',52000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('ADMIN',53000);

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',1);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',2);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',22);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',10000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',11000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',12000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',13000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',14000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',15000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',20000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',21000);


INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',30000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',31000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',40000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',41000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',46000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',50000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_DEPT',51000);


INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_LEADER',1);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_LEADER',2);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_LEADER',22);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_LEADER',20000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_LEADER',21000);

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_LEADER',50000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('SUPER_LEADER',51000);

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT_LEADER',1);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT_LEADER',2);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT_LEADER',22);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT_LEADER',20000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT_LEADER',21000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT_LEADER',22000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT_LEADER',50000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT_LEADER',51000);

 
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',1);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',2);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',22);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',10000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',11000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',12000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',15000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',13000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',20000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',21000);

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',50000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('DEPT',51000);

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',1);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',2);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',22);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',10000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',11000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',13000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',15000);

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',20000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',21000);

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',33000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',50000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('GASSTATION',51000);

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('INFO_DEPT',1);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('INFO_DEPT',40000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('INFO_DEPT',43000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('INFO_DEPT',50000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('INFO_DEPT',51000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('INFO_DEPT',52000);

INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('MANAGE',1);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('MANAGE',20000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('MANAGE',21000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('MANAGE',50000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('MANAGE',51000);
INSERT INTO `role_map_menu`(ROLE,MENU_ID) VALUES ('MANAGE',52000);
