DROP DATABASE IF EXISTS `feugodb`;
CREATE DATABASE `feugodb` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `feugodb`;

DROP TABLE IF EXISTS `system_user`;
CREATE TABLE `system_user` (
  `USER_NAME` varchar(255) NOT NULL COMMENT '用户名称:',
  `PASSWORD` varchar(255) NOT NULL DEFAULT '123456' COMMENT '用户密码:',
  `DEPT_NAME` varchar(255) NOT NULL COMMENT '用户所属部门:',
  `DEPT_ID` varchar(255) NOT NULL COMMENT '部门编码:原系统包含的油站编码（部门MayBe有Maybe没有）',
  `MANAGE_NAME` varchar(255) DEFAULT NULL COMMENT '经营管理部:',
  `ROLE` varchar(255) NOT NULL COMMENT '权限角色:分为4个层级具体见权限说明文档。',
  PRIMARY KEY (`USER_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `menu_tree`;
CREATE TABLE `menu_tree` (
  `MENU_ID` int(32) NOT NULL DEFAULT '0' COMMENT '菜单ID:',
  `NAME` varchar(255) DEFAULT NULL COMMENT '菜单名称:',
  `VALUE` varchar(255) DEFAULT NULL COMMENT '菜单显示值:',
  `MENU_CSS` varchar(255) DEFAULT NULL COMMENT '菜单风格:',
  `ICON_CSS` varchar(255) DEFAULT NULL COMMENT '图标风格:',
  `URL` varchar(255) DEFAULT NULL COMMENT '菜单跳转URL:',
  `PARENT_ID` int(32) DEFAULT NULL COMMENT '上一级菜单ID:',
  PRIMARY KEY (`MENU_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `role_map_menu`;
CREATE TABLE `role_map_menu` (
  `ROLE` varchar(255) NOT NULL COMMENT '角色:',
  `MENU_ID` int(16) NOT NULL COMMENT '菜单ID:',
  PRIMARY KEY (`ROLE`,`MENU_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `physical_assets_status`;
CREATE TABLE `physical_assets_status` (
  `ASSETS_ID` varchar(255) NOT NULL,
  `ASSETS_NAME` varchar(255) NOT NULL,
  `ASSETS_SRC` varchar(255) DEFAULT NULL,
  `MANUFACTURER` varchar(255) DEFAULT NULL,
  `SPEC` varchar(255) DEFAULT NULL,
  `UNIT` varchar(255) DEFAULT NULL,
  `QUANTITY` int(32) DEFAULT NULL,
  `PURCHASE_DATE` date DEFAULT NULL,
  `ORIGINAL_VALUE` float DEFAULT NULL,
  `EXPECT_YEAR` int(32) DEFAULT NULL,
  `DUE_DATE` date DEFAULT NULL,
  `DEPT` varchar(255) DEFAULT NULL,
  `DUTY` varchar(255) DEFAULT NULL,
  `ASSETS_TYPE` varchar(255) DEFAULT NULL,
  `ATTR_TYPE` varchar(255) DEFAULT NULL,
  `LOCATION` varchar(255) DEFAULT NULL,
  `TECH_STATE` varchar(255) DEFAULT NULL,
  `CHECK_DATE` date DEFAULT NULL,
  `NOTE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ASSETS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `trans_event`;
CREATE TABLE `trans_event` (
  `TRANS_ID` varchar(255) NOT NULL,
  `TRANS_NAME` varchar(255) DEFAULT NULL,
  `CREATE_TIME` date DEFAULT NULL,
  `CREATE_USER` varchar(255) DEFAULT NULL,
  `END_TIME` date DEFAULT NULL,
  `HANDLE_USER` varchar(255) DEFAULT NULL,
  `CURRENT_STEP` int(32) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  `PARENT_TRANS_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TRANS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `trans_event_type`;
CREATE TABLE `trans_event_type` (
  `TYPE` varchar(255) NOT NULL,
  `STEP` int(32) DEFAULT NULL,
  `CURRENT_ID` int(32) DEFAULT NULL,
  PRIMARY KEY (`TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `trans_event_type`;
CREATE TABLE `trans_event_type` (
  `TYPE` varchar(255) NOT NULL,
  `STEP` int(32) DEFAULT NULL,
  `CURRENT_ID` int(32) DEFAULT NULL,
  PRIMARY KEY (`TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `check_plan`;
CREATE TABLE `check_plan` (
  `TRANS_ID` varchar(20) NOT NULL,
  `ASSETS_NAME` varchar(255) DEFAULT NULL,
  `MANUFACTURE` varchar(255) DEFAULT NULL,
  `SPEC` varchar(255) DEFAULT NULL,
  `DEPT_ID` varchar(255) NOT NULL,
  `QUANTITY` int(32) DEFAULT NULL,
  `CHECK_CNT` int(32) DEFAULT NULL,
  `CHECK_STATE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TRANS_ID`,`ASSETS_NAME`,`MANUFACTURE`,`SPEC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `purchase_plan`;
CREATE TABLE `purchase_plan` (
  `TRANS_ID` varchar(20) NOT NULL,
  `ASSETS_NAME` varchar(255) DEFAULT NULL,
  `MANUFACTURE` varchar(255) DEFAULT NULL,
  `SPEC` varchar(255) DEFAULT NULL,
  `QUANTITY` int(32) DEFAULT NULL,
  `PRICE` int(32) DEFAULT NULL,
  `SUM` int(32) DEFAULT NULL,
  `NOTE` varchar(255) DEFAULT NULL,
   PRIMARY KEY (`TRANS_ID`,`ASSETS_NAME`,`MANUFACTURE`,`SPEC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `assets_type`;
CREATE TABLE `assets_type` (
  `TYPE_NAME` varchar(255) DEFAULT NULL,
  `TYPE_ID` varchar(255) NOT NULL,
  `ATTR_ID` varchar(255) DEFAULT NULL,
  `ATTR_NAME` varchar(255) DEFAULT NULL,
  `DEPT_ID` varchar(255) DEFAULT NULL,
  `CURRENT_ID` int(32) DEFAULT NULL,
  `PREFIX` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TYPE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
